[build]
builder = "DOCKERFILE"
dockerfilePath = "backend.Dockerfile"

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
